const resList = [
  {
    id: "33040",
    name: "Shah Ghouse Hotel & Restaurant",
    cloudinaryImageId: "hnx9nazpxdpqpypjo8ld",
    locality: "Bio-Diversity Park",
    areaName: "Hitec City",
    costForTwo: "₹350 for two",
    cuisines: ["Biryani", "North Indian", "Chinese", "Mughlai", "Tandoor"],
    avgRating: 4,
    deliveryTime: 23,
  },
  {
    id: "1068",
    name: "Box Eat by Rice Bowl",
    cloudinaryImageId: "4b9596bf72e9f9934bdc6104f5fe7fb8",
    locality: "Telecom Nagar",
    areaName: "Kondapur",
    costForTwo: "₹400 for two",
    cuisines: ["North Indian", "South Indian"],
    avgRating: 4.2,
    deliveryTime: 33,
  },
  {
    id: "324362",
    name: "Tossin Pizza",
    cloudinaryImageId: "313485a665bd0f4958fdc14ead8afade",
    locality: "Gachibowli",
    areaName: "Gachibowli",
    costForTwo: "₹600 for two",
    cuisines: ["Pizzas", "Italian", "Beverages", "Desserts"],
    avgRating: 4,
    deliveryTime: 45,
  },
  {
    id: "10492",
    name: "Pizza Hut",
    cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
    locality: "Madhapur",
    areaName: "Madhapur",
    costForTwo: "₹350 for two",
    cuisines: ["Pizzas"],
    avgRating: 3.6,
    deliveryTime: 36,
  },
  {
    id: "1590",
    name: "Sarvi Restaurant",
    cloudinaryImageId: "ds6nasa6qpxunkhglz5g",
    locality: "Banjara Hills",
    areaName: "Banjara Hills",
    costForTwo: "₹400 FOR TWO",
    cuisines: ["Biryani", "Chinese", "Indian", "Kebabs", "Tandoor", "Desserts"],
    avgRating: 4.2,
    deliveryTime: 43,
  },
  {
    id: "523564",
    name: "Shahi Dastarkhwan",
    cloudinaryImageId: "acwvb2nr6kriqnb5finh",
    locality: "Lakdi-Ka-Pul",
    areaName: "Lakdi-Ka-Pul",
    costForTwo: "₹500 FOR TWO",
    cuisines: ["North Indian", "Chinese", "Kebabs", "Biryani", "Desserts"],
    avgRating: 3.9,
    deliveryTime: 45,
  },
  {
    id: "436805",
    name: "Lucky Multicuisine Restaurant",
    cloudinaryImageId: "n2kt3noplim3agty9ox8",
    locality: "Guttalabegumpet",
    areaName: "Madhapur",
    costForTwo: "₹400 FOR TWO",
    cuisines: ["Biryani", "North Indian", "Tandoor", "South Indian"],
    avgRating: 3.5,
    deliveryTime: 31,
  },
  {
    id: "33096",
    name: "Biryani & Biryani",
    cloudinaryImageId: "mfjuhwmlrpwpougdkv0i",
    locality: "Manikonda",
    areaName: "Neknampur",
    costForTwo: "₹350 FOR TWO",
    cuisines: ["North Indian", "South Indian", "Chinese"],
    avgRating: 3.8,
    deliveryTime: 36,
  },
  {
    id: "27666",
    name: "Pista House Restaurant & Bakery",
    cloudinaryImageId: "qkl7ttnm6x97s8lxjbkf",
    locality: "Gachibowli",
    areaName: "Kondapur",
    costForTwo: "₹400 FOR TWO",
    cuisines: [
      "Biryani",
      "Hyderabadi",
      "North Indian",
      "Tandoor",
      "Mughlai",
      "Chinese",
      "Bakery",
      "Pizzas",
    ],
    avgRating: 4,
    deliveryTime: 28,
  },
  {
    id: "6336",
    name: "Spicy Restaurant",
    cloudinaryImageId: "cdmzv99zcatsejcqtbgb",
    locality: "Indira Nagar Cross Road",
    areaName: "Yousufguda",
    costForTwo: "₹300 FOR TWO",
    cuisines: ["Biryani", "North Indian", "Tandoor"],
    avgRating: 3.8,
    deliveryTime: 31,
  },
  {
    id: "2936",
    name: "Hitex Bawarchi",
    cloudinaryImageId: "ja4jie8kw6wrgcg3r3aa",
    locality: "Bapu Nagar",
    areaName: "Doyens Colony",
    costForTwo: "₹300 FOR TWO",
    cuisines: ["North Indian", "Biryani", "Chinese"],
    avgRating: 3.6,
    deliveryTime: 35,
  },
  {
    id: "1100",
    name: "Santosh Dhaba Exclusive",
    cloudinaryImageId: "tto2pcuxusnezxodomzk",
    address: "2-41/11/1B, Opposite Harsha Toyota, Kondapur",
    locality: "Kothaguda",
    areaName: "Land Mark Residency",
    costForTwo: "₹300 FOR TWO",
    cuisines: ["North Indian", "Chinese"],
    avgRating: 3.8,
    deliveryTime: 26,
  },
];

export default resList;
